version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: mysql:8.0.34
        environment:
          MYSQL_ROOT_PASSWORD: password123
      - image: mcr.microsoft.com/mssql/server:2017-CU31-GDR2-ubuntu-18.04
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: password123
          MSSQL_MEMORY_LIMIT_MB: 1024
    steps:
      - checkout
      - run: echo "hello wowwaaa"
